# Dependabot. The application allows automating dependencies updates.
# It provides information to Dependabot about used package ecosystems.
#
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates.
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - 'type: improvement'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps(dev)'
      include: 'scope'
  - package-ecosystem: npm
    directory: /docs/
    schedule:
      interval: daily
    labels:
      - 'type: improvement'
      - 'scope: docs'
      - 'scope: deps'
    commit-message:
      prefix: 'docs: deps'
      prefix-development: 'docs: deps(dev)'
      include: 'scope'
  - package-ecosystem: gomod
    directory: /tools/
    schedule:
      interval: daily
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'tools: deps'
      include: 'scope'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'ci/cd: deps'
      include: 'scope'
