repository:
  has_wiki: false
  has_issues: true
  has_projects: false

  allow_forking: true

  allow_merge_commit: false
  allow_squash_merge: true
  use_squash_pr_title_as_default: true
  allow_rebase_merge: true
  allow_update_branch: false
  allow_auto_merge: false
  delete_branch_on_merge: true

  default_branch: main

  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

branches:
  - name: main
    protection:
      required_linear_history: true

labels:
  - name: 'type: bug'
    color: '#DA0064'
    description: |
      A new bug report.
  - name: 'type: feature'
    color: '#9510AC'
    description: |
      A new feature request.
  - name: 'type: improvement'
    color: '#0CA789'
    description: |
      A new improvement proposal.

  - name: 'severity: critical'
    color: '#F24727'
    description: |
      A bug has critical severity and needs to be fixed as soon as possible.
  - name: 'severity: major'
    color: '#EF8D79'
    description: |
      A bug has major severity and needs to be fixed in the nearest iteration.
  - name: 'severity: minor'
    color: '#FBC7BD'
    description: |
      A bug has minor severity and should be fixed when possible.

  - name: 'scope: code'
    color: '#808080'
    description: |
      An issue related to source code.
  - name: 'scope: deps'
    color: '#949494'
    description:
      An issue related to dependencies.
  - name: 'scope: docs'
    color: '#ADADAD'
    description: |
      An issue related to documentation.
  - name: 'scope: test'
    color: '#D9D9D9'
    description: |
      An issue related to tests.
  - name: 'scope: inventory'
    color: '#EAEAEA'
    description: |
      An issue related to auxiliary code, e.g., CI config, Makefiles, etc.

  - name: 'impact: high'
    color: '#652CB3'
    description: |
      An issue has high impact.
  - name: 'impact: medium'
    color: '#A380D1'
    description: |
      An issue has medium impact.
  - name: 'impact: low'
    color: '#CAB9E1'
    description: |
      An issue has low impact.

  - name: 'effort: hard'
    color: '#414BB2'
    description: |
      An issue is hard to implement or reproduce.
  - name: 'effort: medium'
    color: '#8D93D1'
    description: |
      An issue has a medium complexity.
  - name: 'effort: easy'
    color: '#C6C9E8'
    description: |
      An issue is easy to implement.

  - name: 'status: pending'
    color: '#2D9BF1'
    description: |
      Mark an issue as hold.
  - name: 'status: stale'
    color: '#3A3A3A'
    description: |
      Mark an issue as stale.

  - name: duplicate
    color: '#F8961E'
    description: |
      An issue or pull request already exists.
  - name: good first issue
    color: '#90BE6D'
    description: |
      Good for newcomers.
  - name: help wanted
    color: '#577590'
    description: |
      Extra attention is needed.
  - name: invalid
    color: '#F94144'
    description: |
      This doesn't seem right.
  - name: question
    color: '#43AA8B'
    description: |
      Further information is requested.
  - name: wontfix
    color: '#F9C74F'
    description: |
      This will not be worked on.
